version: 2
jobs:
  build:
    docker:
      - image: docker:17.10.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: echo "A first hello"
      - run: 
          name: docker pull
          no_output_timeout: 60m
          command: |
            docker pull djarecka/nipype_tutorial:latest
      - run: docker cp test_notebooks.py djarecka/nipype_tutorial:latest:/home/neuro/nipype_tutorial
      - run:
          name: docker run
          no_output_timeout: 60m
          command: |
            docker run -it --rm djarecka/nipype_tutorial pytest /home/neuro/nipype_tutorial/test_notebooks.py
         