version: 2
jobs:
  build:
    docker:
      - image: docker:17.10.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "A first hello"
      - run: 
          name: dicker buils
	  command: |
	    docker build -t djarecka/nipype_tutorial:$CIRCLE_BRANCH .
      - run:
          name: docker run
          command: |
            docker run -it --rm -v $PWD:/home/neuro/nipype_tutorial djarecka/nipype_tutorial:$CIRCLE_BRANCH pytest /home/neuro/nipype_tutorial/test_notebooks.py
         