version: 2
jobs:
  build:
    docker:
      - image: docker:17.10.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: 
          name: docker build
          no_output_timeout: 60m
          command: |
            e=1 && for i in {1..5}; do
               ech "hello" && e=0 && break || sleep 1
            done && [ "$e" -eq "0" ]

         