version: 2
jobs:
  build:
    docker:
      - image: djarecka/nipype_tutorial
    steps:
      - checkout
      - run: echo "A first hello"
      - run:
          name: docker run
          command: |
            docker run -it --rm djarecka/nipype_tutorial
         