version: 2
jobs:
  build:
    docker:
      - image: docker:17.10.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: echo "A first hello"
      - run:
          name: docker run
          command: |
            docker run -it --rm djarecka/nipype_tutorial echo "A second hello"
         