version: 2
jobs:
  build:
    docker:
      - image: docker pull djarecka/nipype_tutorial
    steps:
      - checkout
      - run: echo "A first hello"
      - run:
          name: Change to Python 3.5.2 and install python dependencies
          command: |
            pyenv global 3.5.2
         