name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: generate the Dockerfile from generate.sh
      run: bash generate.sh
    # In this step, this action saves a list of existing images,
    # the cache is created without them in the post run.
    # It also restores the cache if it exists.
    - uses: satackey/action-docker-layer-caching@v0.0.5
    - name: build the image
      run: docker build . --file Dockerfile -t nipype_tutorial:latest

  test_1:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.5
    - name: run tests: introduction
      run: docker run --rm nipype_tutorial:latest pytest --nbval-lax --nbval-cell-timeout 7200 -v -s notebooks/introduction*.ipynb
    - name: run tests: basic
      run: docker run --rm nipype_tutorial:latest pytest --nbval-lax --nbval-cell-timeout 7200 -v -s notebooks/basic*.ipynb
    - name: run tests: advanced
      run: docker run --rm nipype_tutorial:latest pytest --nbval-lax --nbval-cell-timeout 7200 -v -s notebooks/advanced*.ipynb


  test_2:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.5
    - name: prepare tests: examples
      run: docker run --rm nipype_tutorial:latest python /home/neuro/nipype_tutorial/test_notebooks.py 2
    - name: run the tests: examples
      run: docker run --rm nipype_tutorial:latest pytest --nbval-lax --nbval-cell-timeout 7200 -v -s notebooks/example_preprocessing.ipynb notebooks/example_1stlevel.ipynb notebooks/example_normalize.ipynb notebooks/example_2ndlevel.ipynb


  test_3:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: satackey/action-docker-layer-caching@v0.0.5
    - name: prepare tests: handson
      run: docker run --rm nipype_tutorial:latest python /home/neuro/nipype_tutorial/test_notebooks.py 3
    - name: run the tests: handson
      run: docker run --rm nipype_tutorial:latest pytest --nbval-lax --nbval-cell-timeout 7200 -v -s notebooks/handson_preprocessing.ipynb notebooks/handson_analysis.ipynb
